name: Cypress Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1
        
      - name: Clean workspace
        run: rm -rf ./allure-results || true

      - name: Create allure-results directory
        run: mkdir -p ./allure-results
  
      - name: Build Docker containers
        run: docker-compose build

  test_and_report:
    runs-on: ubuntu-latest
    needs: buildx

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Cypress tests
        run: docker-compose run --rm cypress-api npx cypress run -e grepTags=@smoke,allure=true

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results

      - name: Generate and Publish Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report
          allure open allure-report
